import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import pc from 'picocolors';
import { LINKPM_HOME, GLOBAL_BIN_DIR } from './config/index.js';
import { installPackages, type InstallOptions, type InstallResult } from './installer.js';

export interface GlobalInstallOptions extends InstallOptions {
  /** Override the global root (primarily for tests). */
  globalRoot?: string;
  /** Override the global bin directory (primarily for tests). */
  globalBinDir?: string;
}

export interface GlobalInstallResult {
  results: InstallResult[];
  globalRoot: string;
  binDir: string;
  binsCopied: string[];
}

function ensureGlobalPackageJson(globalRoot: string): void {
  const pkgPath = path.join(globalRoot, 'package.json');
  if (!fs.existsSync(pkgPath)) {
    fs.writeFileSync(
      pkgPath,
      JSON.stringify(
        {
          name: 'linkpm-global',
          private: true,
          version: '1.0.0',
          description: 'LinkPM global installations (managed by linkpm add -g)'
        },
        null,
        2
      ) + '\n',
      'utf-8'
    );
  }
}

// Copy the .bin shims generated by linkPackage into a stable global bin dir so
// users only ever need ONE PATH entry (~/.linkpm/bin) regardless of how the
// global virtual store moves.
function copyBinShims(globalRoot: string, binDir: string, binNames: string[]): string[] {
  const srcDir = path.join(globalRoot, 'node_modules', '.bin');
  if (!fs.existsSync(srcDir)) return [];
  if (!fs.existsSync(binDir)) fs.mkdirSync(binDir, { recursive: true });

  const copied = new Set<string>();
  for (const name of binNames) {
    for (const suffix of ['', '.cmd', '.ps1']) {
      const src = path.join(srcDir, `${name}${suffix}`);
      const dest = path.join(binDir, `${name}${suffix}`);
      if (fs.existsSync(src)) {
        try {
          fs.copyFileSync(src, dest);
          if (!suffix && process.platform !== 'win32') {
            try { fs.chmodSync(dest, 0o755); } catch {}
          }
          copied.add(name);
        } catch {}
      }
    }
  }
  return Array.from(copied);
}

/**
 * Installs packages globally (pnpm add -g parity): packages are linked into
 * the shared ~/.linkpm/global project using the central store, and their bin
 * shims are copied to ~/.linkpm/bin.
 */
export async function installGlobalPackages(
  specs: string[],
  options: GlobalInstallOptions = {}
): Promise<GlobalInstallResult> {
  const globalRoot = options.globalRoot || path.join(LINKPM_HOME, 'global');
  const binDir = options.globalBinDir || GLOBAL_BIN_DIR;

  if (!fs.existsSync(globalRoot)) fs.mkdirSync(globalRoot, { recursive: true });
  ensureGlobalPackageJson(globalRoot);

  const { globalRoot: _g, globalBinDir: _b, ...installOpts } = options;
  const results = await installPackages(specs, globalRoot, {
    ...installOpts,
    writeToPackageJson: true,
    persistLockfile: true,
    noPrune: true
  });

  const allBins = results.flatMap(r => r.binsLinked);
  const binsCopied = copyBinShims(globalRoot, binDir, allBins);

  return { results, globalRoot, binDir, binsCopied };
}

/** Prints OS-specific instructions to put the global bin dir on PATH. */
export function printGlobalPathInstructions(binDir: string, bins: string[]): void {
  const home = os.homedir();
  console.log(pc.bold('\n🌐 Global binaries staged in: ') + pc.cyan(binDir));
  if (bins.length > 0) {
    console.log(`  Shims: ${bins.join(', ')}`);
  }
  console.log(pc.bold('\nTo run them from any terminal, add this directory to your PATH (one-time):'));
  if (process.platform === 'win32') {
    console.log(pc.cyan(`  PowerShell (recommended):`));
    console.log(pc.dim(`    [Environment]::SetEnvironmentVariable('Path', $env:PATH + ';${binDir}', 'User')`));
    console.log(pc.cyan(`  cmd.exe:`));
    console.log(pc.dim(`    setx PATH "%PATH%;${binDir}"`));
    console.log(pc.dim(`  (then restart your terminal)`));
  } else {
    const shellRc = (process.env.SHELL || '').includes('zsh') ? '~/.zshrc' : '~/.bashrc';
    console.log(pc.dim(`    echo 'export PATH="${binDir.replace(home, '$HOME')}:$PATH"' >> ${shellRc} && source ${shellRc}`));
  }
  console.log('');
}
